apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yash-repo9576/gitops.git
    targetRevision: HEAD
    path: dev   # Analogy to different env
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops # Namespace to Deploy Application
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true  # Automated Polling the git repository for Overwriting
      prune: true     # Automated Pruning of the kubernetes resources