apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-server
  namespace: gitops
  labels:
    app: taskapp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-server
  template:
    metadata:
      labels:
        app: taskapp-server
    spec:
      containers:
        - name: taskapp-server
          image: ghcr.io/yash-repo9576/taskapp-backend:latest  # Change this to your actual image
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp-server
  namespace: gitops
spec:
  selector:
    app: taskapp-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Change to LoadBalancer if needed for external access
