apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-ui
  namespace: gitops
  labels:
    app: taskapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-ui
  template:
    metadata:
      labels:
        app: taskapp-ui
    spec:
      containers:
        - name: taskapp-ui
          image: ghcr.io/yash-repo9576/taskapp-ui:latest  # Change this to your actual image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp-ui
  namespace: gitops
spec:
  selector:
    app: taskapp-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to LoadBalancer if needed
