apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-ui
  template:
    metadata:
      labels:
        app: taskapp-ui
    spec:
      containers:
      - name: app
        image: ghcr.io/yash-repo9576/taskapp-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: taskapp-ui
spec:
  type: LoadBalancer
  selector:
    app: taskapp-ui
  ports:
  - port: 80
    protocol: TCP
