apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-backend
  template:
    metadata:
      labels:
        app: taskapp-backend
    spec:
      containers:
      - name: server
        image: ghcr.io/yash-repo9576/taskapp-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: taskapp-backend
spec:
  type: ClusterIP
  selector:
    app: taskapp-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
